### ISSUE TITLE
Remove Events class

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-spring-messaging#3]
Events in `Events` class are zipkin specific. They are not needed

**Comment by gytis** [comment]
@pavolloffay should I still log something to the active span (e.g. https://github.com/opentracing-contrib/java-spring-messaging/blob/master/opentracing-spring-messaging/src/main/java/io/opentracing/contrib/spring/integration/messaging/OpenTracingChannelInterceptor.java#L74) or is that unnecessary too?

**Comment by pavolloffay** [comment]
I think it's unnecessary. These events are zipkin specific, for example server send is modeled as span start with an appropriate tag.
