### ISSUE TITLE
Create auto-configurations

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-spring-messaging#4]

**Comment by gytis** [comment]
@pavolloffay what is your normal setup. Keeping the main method vanilla Spring without adding any Boot dependencies and creating auto-configuration somewhere else (e.g. java-spring-cloud). Or is it fine to add it straight to the opentracing-spring-messaging module?

**Comment by pavolloffay** [comment]
so far we always have a starter module with auto-configs
